{
  "swagger": "2.0",
  "info": {
    "title": "Customer API",
    "version": "2.0",
    "description": "This a customer API"
  },
  "paths": {
    "/customer/{id}": {
      "post": {
        "responses": {
          "201": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {}
            },
            "examples": {
              "application/json": {}
            }
          }
        },
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/customer"
            },
            "x-examples": {
              "application/json": {
                "customerid": "2322434",
                "name": "laura",
                "address": "342 Sandstone Dr",
                "phone": "555-555-5555"
              }
            }
          },
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "required": true,
            "default": "234234"
          }
        ]
      },
      "head": {
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {}
            }
          }
        },
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "required": true,
            "default": "234234"
          }
        ]
      },
      "options": {
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {}
            },
            "headers": {
              "allow": {
                "type": "string",
                "default": "OPTIONS, GET, HEAD, DELETE, POST, PUT"
              }
            }
          }
        },
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "required": true,
            "default": "234234"
          }
        ]
      },
      "put": {
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {}
            }
          }
        },
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/customer"
            },
            "x-examples": {
              "application/json": {
                "customerid": "234234",
                "name": "Laura Heritage",
                "address": "33 Park Ave",
                "phone": "555-555-5555"
              }
            }
          },
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "required": true,
            "default": "234234"
          }
        ]
      },
      "delete": {
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {}
            }
          }
        },
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "required": true,
            "default": "234234"
          }
        ]
      },
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "type": "string",
          "required": true
        }
      ],
      "get": {
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/customer"
            },
            "examples": {
              "application/json": {
                "customerid": "234234",
                "name": "Laura Heritage",
                "address": "33 Park Ave",
                "phone": "555-555-5555"
              }
            }
          }
        },
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "required": true,
            "default": "234234"
          }
        ]
      }
    },
    "/customer": {
      "get": {
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/customercollection"
            },
            "examples": {
              "application/json": {
                "customer": [
                  {
                    "customerid": "234234",
                    "name": "Laura Heritage",
                    "address": "33 Park Ave",
                    "phone": "555-555-5555"
                  },
                  {
                    "customerid": "555543",
                    "name": "Sam Smith",
                    "address": "2344 4th St",
                    "phone": "777-777-7777"
                  }
                ]
              }
            }
          }
        },
        "parameters": []
      },
      "post": {
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/customer"
            },
            "examples": {
              "application/json": {
                "customerid": "234234",
                "name": "Laura Heritage",
                "address": "33 Park Ave",
                "phone": "555-555-5555"
              }
            }
          }
        },
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/customer"
            },
            "x-examples": {
              "application/json": {
                "customerid": "esse officia",
                "name": "deserunt veniam Ut labore",
                "address": "veniam",
                "phone": "sint et non consectetur incididunt"
              }
            }
          }
        ]
      },
      "put": {
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {}
            }
          }
        }
      }
    }
  },
  "host": "29cb97a52bb0ce90392e32651cf74a50d46e4eaa.cloudapp-enterprise.appcelerator.com",
  "definitions": {
    "customer": {
      "type": "object",
      "description": "Customer",
      "title": "customer",
      "properties": {
        "customerid": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "city": {
          "type": "string"
        }
      }
    },
    "customercollection": {
      "type": "object",
      "title": "customercollection",
      "properties": {
        "customer": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/customer"
          }
        }
      }
    }
  },
  "basePath": "/api"
}